### ISSUE TITLE
hi ,how to convert mixamo animation to ready player me avatar

### ISSUE THREAD

**Issue by Frankling** [wonglok/effctnode-forge#1]
hi ,how to convert mixamo animation to ready player me avatar

**Comment by wonglok** [comment]
[RPM_Avatar_Reference.fbx.zip](https://github.com/wonglok/effctnode-forge/files/9886655/RPM_Avatar_Reference.fbx.zip)
hi dear try this upload to mixamo you should be able to use the same animation and apply to rpm glb avatar
